### ISSUE TITLE
Doesn't work on windows????

### ISSUE THREAD

**Issue by Devices** [Eryla/dmenyuu#2]
I tried to put a menu on my anime but it didn't seem to do anything.
OS: Microsoft Windows 8.1
CPU: intel i5 760
GPU: Nvidia 560ti
Mouse: logitech m512
Keyboard: some cheap acer thing
Underwear: puple

**Comment by Eryla** [comment]
ty for reporting, I think there is an issue with your shit taste and not dmenyuu.
